# Generated by Django 4.1.3 on 2022-11-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendman', '0002_template_sendhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='list',
            field=models.ManyToManyField(blank=True, to='sendman.subscriberlist', verbose_name='Список'),
        ),
    ]
