# Generated by Django 4.1.3 on 2022-11-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendman', '0003_alter_subscriber_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История отправок', 'verbose_name_plural': 'Истории отправок'},
        ),
        migrations.AddField(
            model_name='subscriberlist',
            name='subscribers',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(help_text='.html', upload_to='templates/', verbose_name='Макет (.html)'),
        ),
    ]
