# Generated by Django 4.1.3 on 2022-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendman', '0004_alter_sendhistory_options_subscriberlist_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
